import "dotenv/config";
import {
  Client,
    GatewayIntentBits,
      Events,
        REST,
          Routes,
            SlashCommandBuilder
            } from "discord.js";
            import OpenAI from "openai";

            const {
              DISCORD_TOKEN,
                CLIENT_ID,
                  GUILD_ID,
                    AI_API_KEY,
                      AI_MODEL = "gpt-5.6-luna"
                      } = process.env;

                      const required = {
                        DISCORD_TOKEN,
                          CLIENT_ID,
                            GUILD_ID,
                              AI_API_KEY
                              };

                              const missing = Object.keys(required).filter(
                                key => !required[key]
                                );

                                if (missing.length > 0) {
                                  console.error("Missing environment variables:");
                                    console.error(missing.join(", "));
                                      process.exit(1);
                                      }

                                      const openai = new OpenAI({
                                        apiKey: AI_API_KEY
                                        });

                                        const client = new Client({
                                          intents: [
                                              GatewayIntentBits.Guilds,
                                                  GatewayIntentBits.GuildMessages,
                                                      GatewayIntentBits.MessageContent
                                                        ]
                                                        });

                                                        const conversations = new Map();
                                                        const cooldowns = new Map();

                                                        const COOLDOWN = 3000;
                                                        const MAX_MESSAGES = 12;

                                                        const LUCY_PROMPT = `
                                                        You are Lucy, a friendly AI Discord chatbot.

                                                        You are female, age 18-20, funny, confident, playful,
                                                        slightly chaotic, and have a natural Gen-Z personality.

                                                        Talk naturally like a Gen-Z friend. Use slang such as
                                                        bro, nah, fr, ngl, lmao, 💀 and 😭 when it fits.
                                                        Do not force slang into every response.

                                                        You enjoy talking about sports, movies, web shows, anime,
                                                        games, music, memes, internet culture, school and random topics.

                                                        Have your own opinions. Do not blindly agree with users.
                                                        Understand jokes, sarcasm and memes.

                                                        You may lightly roast users when appropriate, but never be
                                                        hateful, abusive or genuinely cruel.

                                                        If someone is upset or discussing something serious,
                                                        be supportive rather than roasting them.

                                                        If someone jokingly asks you to date them, reject them
                                                        playfully and kindly. Do not act as their romantic partner.

                                                        Keep everything completely NSFW-free.

                                                        Never claim to be human. You are an AI named Lucy.

                                                        Avoid repetitive responses and keep conversations natural.
                                                        `;

                                                        function isOnCooldown(userId) {
                                                          const now = Date.now();
                                                            const last = cooldowns.get(userId) || 0;

                                                              if (now - last < COOLDOWN) {
                                                                  return true;
                                                                    }

                                                                      cooldowns.set(userId, now);
                                                                        return false;
                                                                        }

                                                                        function getHistory(userId) {
                                                                          if (!conversations.has(userId)) {
                                                                              conversations.set(userId, []);
                                                                                }

                                                                                  return conversations.get(userId);
                                                                                  }

                                                                                  async function askLucy(userId, message) {
                                                                                    const history = getHistory(userId);

                                                                                      history.push({
                                                                                          role: "user",
                                                                                              content: message
                                                                                                });

                                                                                                  while (history.length > MAX_MESSAGES) {
                                                                                                      history.shift();
                                                                                                        }

                                                                                                          try {
                                                                                                              const response = await openai.responses.create({
                                                                                                                    model: AI_MODEL,
                                                                                                                          instructions: LUCY_PROMPT,
                                                                                                                                input: history,
                                                                                                                                      max_output_tokens: 250
                                                                                                                                          });

                                                                                                                                              const reply = response.output_text?.trim();

                                                                                                                                                  if (!reply) {
                                                                                                                                                        throw new Error("OpenAI returned an empty response.");
                                                                                                                                                            }

                                                                                                                                                                history.push({
                                                                                                                                                                      role: "assistant",
                                                                                                                                                                            content: reply
                                                                                                                                                                                });

                                                                                                                                                                                    return reply;
                                                                                                                                                                                      } catch (error) {
                                                                                                                                                                                          console.error("========== OPENAI ERROR ==========");
                                                                                                                                                                                              console.error("Status:", error.status || "Unknown");
                                                                                                                                                                                                  console.error("Message:", error.message || error);
                                                                                                                                                                                                      console.error("==================================");

                                                                                                                                                                                                          throw error;
                                                                                                                                                                                                            }
                                                                                                                                                                                                            }

                                                                                                                                                                                                            const commands = [
                                                                                                                                                                                                              new SlashCommandBuilder()
                                                                                                                                                                                                                  .setName("chat")
                                                                                                                                                                                                                      .setDescription("Talk to Lucy")
                                                                                                                                                                                                                          .addStringOption(option =>
                                                                                                                                                                                                                                option
                                                                                                                                                                                                                                        .setName("message")
                                                                                                                                                                                                                                                .setDescription("Your message")
                                                                                                                                                                                                                                                        .setRequired(true)
                                                                                                                                                                                                                                                                .setMaxLength(1000)
                                                                                                                                                                                                                                                                    ),

                                                                                                                                                                                                                                                                      new SlashCommandBuilder()
                                                                                                                                                                                                                                                                          .setName("reset")
                                                                                                                                                                                                                                                                              .setDescription("Reset your conversation with Lucy")
                                                                                                                                                                                                                                                                              ].map(command => command.toJSON());

                                                                                                                                                                                                                                                                              async function registerCommands() {
                                                                                                                                                                                                                                                                                const rest = new REST({ version: "10" })
                                                                                                                                                                                                                                                                                    .setToken(DISCORD_TOKEN);

                                                                                                                                                                                                                                                                                      await rest.put(
                                                                                                                                                                                                                                                                                          Routes.applicationGuildCommands(
                                                                                                                                                                                                                                                                                                CLIENT_ID,
                                                                                                                                                                                                                                                                                                      GUILD_ID
                                                                                                                                                                                                                                                                                                          ),
                                                                                                                                                                                                                                                                                                              {
                                                                                                                                                                                                                                                                                                                    body: commands
                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                          );

                                                                                                                                                                                                                                                                                                                            console.log("Slash commands registered.");
                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                            client.once(Events.ClientReady, async readyClient => {
                                                                                                                                                                                                                                                                                                                              console.log(`Lucy is online as ${readyClient.user.tag}`);

                                                                                                                                                                                                                                                                                                                                try {
                                                                                                                                                                                                                                                                                                                                    await registerCommands();
                                                                                                                                                                                                                                                                                                                                      } catch (error) {
                                                                                                                                                                                                                                                                                                                                          console.error("Command registration error:", error);
                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                            });

                                                                                                                                                                                                                                                                                                                                            client.on(Events.InteractionCreate, async interaction => {
                                                                                                                                                                                                                                                                                                                                              if (!interaction.isChatInputCommand()) {
                                                                                                                                                                                                                                                                                                                                                  return;
                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                      if (interaction.commandName === "reset") {
                                                                                                                                                                                                                                                                                                                                                          conversations.delete(interaction.user.id);

                                                                                                                                                                                                                                                                                                                                                              await interaction.reply({
                                                                                                                                                                                                                                                                                                                                                                    content: "Memory reset 😭 We starting fresh.",
                                                                                                                                                                                                                                                                                                                                                                          ephemeral: true
                                                                                                                                                                                                                                                                                                                                                                              });

                                                                                                                                                                                                                                                                                                                                                                                  return;
                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                      if (interaction.commandName !== "chat") {
                                                                                                                                                                                                                                                                                                                                                                                          return;
                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                              if (isOnCooldown(interaction.user.id)) {
                                                                                                                                                                                                                                                                                                                                                                                                  await interaction.reply({
                                                                                                                                                                                                                                                                                                                                                                                                        content: "Bro slow down 😭 Give me a second.",
                                                                                                                                                                                                                                                                                                                                                                                                              ephemeral: true
                                                                                                                                                                                                                                                                                                                                                                                                                  });

                                                                                                                                                                                                                                                                                                                                                                                                                      return;
                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                          const message = interaction.options.getString("message");

                                                                                                                                                                                                                                                                                                                                                                                                                            await interaction.deferReply();

                                                                                                                                                                                                                                                                                                                                                                                                                              try {
                                                                                                                                                                                                                                                                                                                                                                                                                                  const reply = await askLucy(
                                                                                                                                                                                                                                                                                                                                                                                                                                        interaction.user.id,
                                                                                                                                                                                                                                                                                                                                                                                                                                              message
                                                                                                                                                                                                                                                                                                                                                                                                                                                  );

                                                                                                                                                                                                                                                                                                                                                                                                                                                      await interaction.editReply(reply);
                                                                                                                                                                                                                                                                                                                                                                                                                                                        } catch (error) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                            await interaction.editReply(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  "Nahhh my AI brain crashed 💀 Try again."
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                        client.on(Events.MessageCreate, async message => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          if (message.author.bot) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              return;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  if (!client.user) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      return;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          if (!message.mentions.has(client.user)) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              return;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  if (isOnCooldown(message.author.id)) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      return;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          const mentionRegex = new RegExp(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              `<@!?${client.user.id}>`,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  "g"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    );

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      const content = message.content
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          .replace(mentionRegex, "")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              .trim();

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if (!content) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    await message.reply(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          "Yo 😭 you summoned me for nothing?"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              );

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  return;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      try {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          await message.channel.sendTyping();

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              const reply = await askLucy(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    message.author.id,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          content
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              );

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  await message.reply(reply);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    } catch (error) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        console.error(error);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            await message.reply(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  "Bro my AI brain is taking a nap 💀 Try again."
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        client.login(DISCORD_TOKEN);